#pragma once

#define INCLUDE_EXTRA_MODULES
#include <opencv2\opencv.hpp>

#ifdef _WIN64

#ifdef _DEBUG

#pragma comment(lib, "x64\\opencv_calib3d310d.lib")
#pragma comment(lib, "x64\\opencv_core310d.lib")
#pragma comment(lib, "x64\\opencv_datasets310d.lib")
#pragma comment(lib, "x64\\opencv_features2d310d.lib")
#pragma comment(lib, "x64\\opencv_flann310d.lib")
#pragma comment(lib, "x64\\opencv_highgui310d.lib")
#pragma comment(lib, "x64\\opencv_imgcodecs310d.lib")
#pragma comment(lib, "x64\\opencv_imgproc310d.lib")
#pragma comment(lib, "x64\\opencv_ml310d.lib")
#pragma comment(lib, "x64\\opencv_objdetect310d.lib")
#pragma comment(lib, "x64\\opencv_photo310d.lib")
#pragma comment(lib, "x64\\opencv_reg310d.lib")
#pragma comment(lib, "x64\\opencv_shape310d.lib")
#pragma comment(lib, "x64\\opencv_stitching310d.lib")
#pragma comment(lib, "x64\\opencv_superres310d.lib")
#pragma comment(lib, "x64\\opencv_ts310d.lib")
#pragma comment(lib, "x64\\opencv_video310d.lib")
#pragma comment(lib, "x64\\opencv_videoio310d.lib")
#pragma comment(lib, "x64\\opencv_videostab310d.lib")
#else
#pragma comment(lib, "x64\\opencv_calib3d310.lib")
#pragma comment(lib, "x64\\opencv_core310.lib")
#pragma comment(lib, "x64\\opencv_datasets310.lib")
#pragma comment(lib, "x64\\opencv_features2d310.lib")
#pragma comment(lib, "x64\\opencv_flann310.lib")
#pragma comment(lib, "x64\\opencv_highgui310.lib")
#pragma comment(lib, "x64\\opencv_imgcodecs310.lib")
#pragma comment(lib, "x64\\opencv_imgproc310.lib")
#pragma comment(lib, "x64\\opencv_ml310.lib")
#pragma comment(lib, "x64\\opencv_objdetect310.lib")
#pragma comment(lib, "x64\\opencv_photo310.lib")
#pragma comment(lib, "x64\\opencv_reg310.lib")
#pragma comment(lib, "x64\\opencv_shape310.lib")
#pragma comment(lib, "x64\\opencv_stitching310.lib")
#pragma comment(lib, "x64\\opencv_superres310.lib")
#pragma comment(lib, "x64\\opencv_ts310.lib")
#pragma comment(lib, "x64\\opencv_video310.lib")
#pragma comment(lib, "x64\\opencv_videoio310.lib")
#pragma comment(lib, "x64\\opencv_videostab310.lib")
#endif // DEBUG

#else

#ifdef _DEBUG
#pragma comment(lib, "x86\\opencv_calib3d310d.lib")
#pragma comment(lib, "x86\\opencv_core310d.lib")
#pragma comment(lib, "x86\\opencv_datasets310d.lib")
#pragma comment(lib, "x86\\opencv_features2d310d.lib")
#pragma comment(lib, "x86\\opencv_flann310d.lib")
#pragma comment(lib, "x86\\opencv_highgui310d.lib")
#pragma comment(lib, "x86\\opencv_imgcodecs310d.lib")
#pragma comment(lib, "x86\\opencv_imgproc310d.lib")
#pragma comment(lib, "x86\\opencv_ml310d.lib")
#pragma comment(lib, "x86\\opencv_objdetect310d.lib")
#pragma comment(lib, "x86\\opencv_photo310d.lib")
#pragma comment(lib, "x86\\opencv_reg310d.lib")
#pragma comment(lib, "x86\\opencv_shape310d.lib")
#pragma comment(lib, "x86\\opencv_stitching310d.lib")
#pragma comment(lib, "x86\\opencv_superres310d.lib")
#pragma comment(lib, "x86\\opencv_ts310d.lib")
#pragma comment(lib, "x86\\opencv_video310d.lib")
#pragma comment(lib, "x86\\opencv_videoio310d.lib")
#pragma comment(lib, "x86\\opencv_videostab310d.lib")
#else
#pragma comment(lib, "x86\\opencv_calib3d310.lib")
#pragma comment(lib, "x86\\opencv_core310.lib")
#pragma comment(lib, "x86\\opencv_datasets310.lib")
#pragma comment(lib, "x86\\opencv_features2d310.lib")
#pragma comment(lib, "x86\\opencv_flann310.lib")
#pragma comment(lib, "x86\\opencv_highgui310.lib")
#pragma comment(lib, "x86\\opencv_imgcodecs310.lib")
#pragma comment(lib, "x86\\opencv_imgproc310.lib")
#pragma comment(lib, "x86\\opencv_ml310.lib")
#pragma comment(lib, "x86\\opencv_objdetect310.lib")
#pragma comment(lib, "x86\\opencv_photo310.lib")
#pragma comment(lib, "x86\\opencv_reg310.lib")
#pragma comment(lib, "x86\\opencv_shape310.lib")
#pragma comment(lib, "x86\\opencv_stitching310.lib")
#pragma comment(lib, "x86\\opencv_superres310.lib")
#pragma comment(lib, "x86\\opencv_ts310.lib")
#pragma comment(lib, "x86\\opencv_video310.lib")
#pragma comment(lib, "x86\\opencv_videoio310.lib")
#pragma comment(lib, "x86\\opencv_videostab310.lib")
#endif // DEBUG

#endif



#ifdef INCLUDE_EXTRA_MODULES //extra modules add by yn
#ifdef _WIN64

#ifdef _DEBUG
#pragma comment(lib, "x64\\opencv_aruco310d.lib")
#pragma comment(lib, "x64\\opencv_bgsegm310d.lib")
#pragma comment(lib, "x64\\opencv_bioinspired310d.lib")
#pragma comment(lib, "x64\\opencv_ccalib310d.lib")
#pragma comment(lib, "x64\\opencv_dnn310d.lib")
#pragma comment(lib, "x64\\opencv_dpm310d.lib")
#pragma comment(lib, "x64\\opencv_face310d.lib")
#pragma comment(lib, "x64\\opencv_fuzzy310d.lib")
#pragma comment(lib, "x64\\opencv_line_descriptor310d.lib")
#pragma comment(lib, "x64\\opencv_optflow310d.lib")
#pragma comment(lib, "x64\\opencv_plot310d.lib")
#pragma comment(lib, "x64\\opencv_rgbd310d.lib")
#pragma comment(lib, "x64\\opencv_saliency310d.lib")
#pragma comment(lib, "x64\\opencv_stereo310d.lib")
#pragma comment(lib, "x64\\opencv_structured_light310d.lib")
#pragma comment(lib, "x64\\opencv_surface_matching310d.lib")
#pragma comment(lib, "x64\\opencv_text310d.lib")
#pragma comment(lib, "x64\\opencv_tracking310d.lib")
#pragma comment(lib, "x64\\opencv_xfeatures2d310d.lib")
#pragma comment(lib, "x64\\opencv_ximgproc310d.lib")
#pragma comment(lib, "x64\\opencv_xobjdetect310d.lib")
#pragma comment(lib, "x64\\opencv_xphoto310d.lib")
#else
#pragma comment(lib, "x64\\opencv_aruco310.lib")
#pragma comment(lib, "x64\\opencv_bgsegm310.lib")
#pragma comment(lib, "x64\\opencv_bioinspired310.lib")
#pragma comment(lib, "x64\\opencv_ccalib310.lib")
#pragma comment(lib, "x64\\opencv_dnn310.lib")
#pragma comment(lib, "x64\\opencv_dpm310.lib")
#pragma comment(lib, "x64\\opencv_face310.lib")
#pragma comment(lib, "x64\\opencv_fuzzy310.lib")
#pragma comment(lib, "x64\\opencv_line_descriptor310.lib")
#pragma comment(lib, "x64\\opencv_optflow310.lib")
#pragma comment(lib, "x64\\opencv_plot310.lib")
#pragma comment(lib, "x64\\opencv_rgbd310.lib")
#pragma comment(lib, "x64\\opencv_saliency310.lib")
#pragma comment(lib, "x64\\opencv_stereo310.lib")
#pragma comment(lib, "x64\\opencv_structured_light310.lib")
#pragma comment(lib, "x64\\opencv_surface_matching310.lib")
#pragma comment(lib, "x64\\opencv_text310.lib")
#pragma comment(lib, "x64\\opencv_tracking310.lib")
#pragma comment(lib, "x64\\opencv_xfeatures2d310.lib")
#pragma comment(lib, "x64\\opencv_ximgproc310.lib")
#pragma comment(lib, "x64\\opencv_xobjdetect310.lib")
#pragma comment(lib, "x64\\opencv_xphoto310.lib")
#endif // DEBUG

#else

#ifdef _DEBUG
#pragma comment(lib, "x86\\opencv_aruco310d.lib")
#pragma comment(lib, "x86\\opencv_bgsegm310d.lib")
#pragma comment(lib, "x86\\opencv_bioinspired310d.lib")
#pragma comment(lib, "x86\\opencv_ccalib310d.lib")
#pragma comment(lib, "x86\\opencv_dnn310d.lib")
#pragma comment(lib, "x86\\opencv_dpm310d.lib")
#pragma comment(lib, "x86\\opencv_face310d.lib")
#pragma comment(lib, "x86\\opencv_fuzzy310d.lib")
#pragma comment(lib, "x86\\opencv_line_descriptor310d.lib")
#pragma comment(lib, "x86\\opencv_optflow310d.lib")
#pragma comment(lib, "x86\\opencv_plot310d.lib")
#pragma comment(lib, "x86\\opencv_rgbd310d.lib")
#pragma comment(lib, "x86\\opencv_saliency310d.lib")
#pragma comment(lib, "x86\\opencv_stereo310d.lib")
#pragma comment(lib, "x86\\opencv_structured_light310d.lib")
#pragma comment(lib, "x86\\opencv_surface_matching310d.lib")
#pragma comment(lib, "x86\\opencv_text310d.lib")
#pragma comment(lib, "x86\\opencv_tracking310d.lib")
#pragma comment(lib, "x86\\opencv_xfeatures2d310d.lib")
#pragma comment(lib, "x86\\opencv_ximgproc310d.lib")
#pragma comment(lib, "x86\\opencv_xobjdetect310d.lib")
#pragma comment(lib, "x86\\opencv_xphoto310d.lib")
#else
#pragma comment(lib, "x86\\opencv_aruco310.lib")
#pragma comment(lib, "x86\\opencv_bgsegm310.lib")
#pragma comment(lib, "x86\\opencv_bioinspired310.lib")
#pragma comment(lib, "x86\\opencv_ccalib310.lib")
#pragma comment(lib, "x86\\opencv_dnn310.lib")
#pragma comment(lib, "x86\\opencv_dpm310.lib")
#pragma comment(lib, "x86\\opencv_face310.lib")
#pragma comment(lib, "x86\\opencv_fuzzy310.lib")
#pragma comment(lib, "x86\\opencv_line_descriptor310.lib")
#pragma comment(lib, "x86\\opencv_optflow310.lib")
#pragma comment(lib, "x86\\opencv_plot310.lib")
#pragma comment(lib, "x86\\opencv_rgbd310.lib")
#pragma comment(lib, "x86\\opencv_saliency310.lib")
#pragma comment(lib, "x86\\opencv_stereo310.lib")
#pragma comment(lib, "x86\\opencv_structured_light310.lib")
#pragma comment(lib, "x86\\opencv_surface_matching310.lib")
#pragma comment(lib, "x86\\opencv_text310.lib")
#pragma comment(lib, "x86\\opencv_tracking310.lib")
#pragma comment(lib, "x86\\opencv_xfeatures2d310.lib")
#pragma comment(lib, "x86\\opencv_ximgproc310.lib")
#pragma comment(lib, "x86\\opencv_xobjdetect310.lib")
#pragma comment(lib, "x86\\opencv_xphoto310.lib")
#endif // DEBUG

#endif
#endif